### ISSUE TITLE
Question: will there be a persistent LinkedHashMap?

### ISSUE THREAD

**Issue by yuriykulikov** [Kotlin/kotlinx.collections.immutable#27]
Hallo everyone,
I have a question, which could probably be answered by @qurbonzoda 

Are there any plans to implement a persistent LinkedHashMap? If yes, which complexity will put and remove functions have? O(n)?

Please close or delete the issue as soon as the question is answered. Thank you.

**Comment by qurbonzoda** [comment]
Hi @yuriykulikov,
Yes. It is already implemented in my pull request, with [this commit](
https://github.com/Kotlin/kotlinx.collections.immutable/pull/20/commits/24c34dbc97e346aeea30e7ca218297bc7b7ec3b2).
The implementation have "effectively constant" time complexity - about 2-3 times slower than persistent HashMap.

**Comment by ilya-g** [comment]
Yes, we're going to have a persistent map that preserves the insertion order during iteration, and also considering to make it the default implementation of the immutable map.

Regarding `put` and `remove` time complexity, it is not effectively constant but rather O(log N), though the log base is rather big here (32).

This comes at a price of increased full iteration time complexity: it is O(N * log N) instead of O(N) as in unordered map.
