### ISSUE TITLE
Clashing method names with `java.util.collections.*`

### ISSUE THREAD

**Issue by belyaev-mikhail** [Kotlin/kotlinx.collections.immutable#3]
Names like `add`, `remove` and `removeAll` are, of course, appropriate names for corresponding operations.
But you should really, REALLY reconsider using these names. Each of your persistent collections is a far descendant of `java.util.collections.Collection<E>` and these names do override the respective methods in that interface with inappropriate result types, even though Kotlin does its magic to hide these behind the immutable `kotlin.smth.Collection<E>` interface.
This name clash may not be a problem now, but it already is the sole reason why your library does not compile with current Kotlin release (1.0.3) and does not work correctly with current Idea Plugin (see screenshot).
And with a small change to Kotlin ABI or a different JVM it may resurface when you least expect it.

![idea_screen](https://cloud.githubusercontent.com/assets/2496075/17004421/897f4ca0-4edd-11e6-87e4-36bde350203b.png)

**Comment by ilya-g** [comment]
There were some problems in Kotlin 1.0.3 handling this situation, but thanks to @dzharkov they all are  fixed now in master branch and those fixes might already be backported to 1.0.x branch. 
So currently koltinx.collections.immutable could be compiled only with the fresh Kotlin build, but later we plan to switch to more stable compiler version, like 1.1-M2 or even 1.0.4.

We're aware that our modification methods hide the methods of `java.util.Collection` with the same name, but since it's allowed by JVM we do not expect it would cause problems when being used from Kotlin.
And our tests also show these immutable collections could be used from Java, see [ImmutableListJavaTest.java](../blob/master/kotlinx-collections-immutable/tests/src/test/kotlin/kotlinx.collections.immutable/ImmutableListJavaTest.java) for example.

If you have a concrete example where such name clash would cause problems, please share it.

**Comment by belyaev-mikhail** [comment]
Okay, so it is a deliberate decision. Seems legit.
> one cannot implement both MutableCollection and ImmutableCollection in the same class. Though it seems not so bad, considering such implementation makes no sense.

Actually, it may well make sense. There are data structures that can be an efficient implementation of both an ephemeral and persistent collection with useful properties, e.g. a segment tree or an implicit treap. It is all a matter of usage pattern, not the structures themselves.
But, of course, you can always resolve this problem using delegation.

> Second is like the first one but from Java side: an ImmutableCollection could not be implemented in Java

Actually, it seems that you can as long as you don't try to override the Collection's base methods. I just tried it. Still don't get how it's possible (java 8 default methods hidden somewhere in Kotlin's Collection interface?).
