### ISSUE TITLE
Are there any plans to support another Native targets?

### ISSUE THREAD

**Issue by arkivanov** [Kotlin/kotlinx.collections.immutable#79]
Hello! This library looks great but I'm interested in some targets that are currently not supported. 
Missing targets that I'm interested in:
- `watchosArm32`
- `watchosArm64`
- `watchosX86`
- `tvosArm64`
- `tvosX64`
- `linuxArm32Hfp`
- `linuxArm64`

**Comment by qurbonzoda** [comment]
Thanks for your enthusiasm @arkivanov !

Adding a corresponding target requires dedicated TeamCity agents (whether bare-metal or properly virtualized) that are capable of running arm32.

Configuring such agents requires serious effort from our build team (in order to make them consistent, cloneable, observable), and, frankly speaking, their resources are seriously limited right now, especially in the face of upcoming Kotlin 1.4 release. Long story short, currently we neither have an infrastructure to test and release arm binaries on a regular basis nor resources to establish such infrastructure. We'll return to this problem right after Kotlin 1.4 post-release activities.

For now, the easiest solution will be to publish these binaries on your own side, either in your organization bintray or directly in maven local of the target machine (if you are going to build your native app right there).
It can be achieved by adjusting the library version in gradle.proprerties and adding the corresponding target to core/build.gradle.kts. Feel free to ask any questions if you are struggling with building it locally.

**Comment by lokedhs** [comment]
I found this issue after having the same problem. I need to build for a Raspbery Pi (in other words, I need to build linuxArm64).

@qurbonzoda I understand the complications of the build chain, and I understand I have to take the approach you suggested in your reply. As far as I understand, I have to either set up my own bintray, which means I have to make it publicly available since I make use of Github actions to run my testcases. My project is open source so it would be nice to not have to manage extra infrastructure.

Ideally I'd like to avoid that and instead somehow convince my local Gradle configuration to build collections-immutable as well, possibly by making collections-immutable a submodule of my main code. Is there a straightforward way to achieve this? I don't want to make you waste too much time, so if this is possible, a reference to the appropriate documentation would be very helpful.

**Comment by arkivanov** [comment]
Btw I configured arm32hfp tests for Reaktive using GitHub actions [here](https://github.com/badoo/Reaktive/blob/cba3858b0336ec79edc0de9b8724cecfaf52874e/.github/workflows/build.yml#L30). It is relatively easy actually. There are two jobs, one links kexe using Ubuntu host, and another runs kexe in an emulator provided by `uraimo/run-on-arch-action`. Maybe it could be useful here as well.

**Comment by qurbonzoda** [comment]
Support for additional Native targets was added in the 0.3.5 version of the library. Please try it out. Thanks for feedback!
